-- Historical stop sensor readings. Safe to run against the existing table.
-- The controller worker appends one snapshot of all readings every 60 seconds.

CREATE TABLE IF NOT EXISTS public.stop_sensor_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bus_stop_id BIGINT NOT NULL,
  element INTEGER NOT NULL,
  address INTEGER NOT NULL DEFAULT 0,
  category TEXT,
  name TEXT,
  value DOUBLE PRECISION,
  alarm TEXT,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'stop_sensor_history_bus_stop_id_fkey'
      AND conrelid = 'public.stop_sensor_history'::regclass
  ) THEN
    ALTER TABLE public.stop_sensor_history
      ADD CONSTRAINT stop_sensor_history_bus_stop_id_fkey
      FOREIGN KEY (bus_stop_id) REFERENCES public.bus_stops(id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_stop_sensor_history_recorded_at
  ON public.stop_sensor_history(recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_stop_sensor_history_bus_stop_time
  ON public.stop_sensor_history(bus_stop_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_stop_sensor_history_sensor_time
  ON public.stop_sensor_history(bus_stop_id, element, category, recorded_at DESC);

ALTER TABLE public.stop_sensor_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read sensor history" ON public.stop_sensor_history;
CREATE POLICY "Allow public read sensor history"
  ON public.stop_sensor_history FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow service role write sensor history" ON public.stop_sensor_history;
CREATE POLICY "Allow service role write sensor history"
  ON public.stop_sensor_history FOR ALL TO service_role USING (true) WITH CHECK (true);

REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
  ON public.stop_sensor_history FROM anon, authenticated;
GRANT SELECT ON public.stop_sensor_history TO anon, authenticated;
GRANT ALL ON public.stop_sensor_history TO service_role;

DO $$
DECLARE
  sequence_name TEXT;
BEGIN
  sequence_name := pg_get_serial_sequence('public.stop_sensor_history', 'id');
  IF sequence_name IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', sequence_name);
  END IF;
END $$;

COMMENT ON TABLE public.stop_sensor_history IS
  'Append-only one-minute history of controller sensor readings for stop analytics.';
COMMENT ON COLUMN public.stop_sensor_history.recorded_at IS
  'UTC timestamp shared by all readings in the same controller snapshot.';

NOTIFY pgrst, 'reload schema';
